load("@rules_python//python:defs.bzl", "py_library")

# gazelle:resolve py lib.check_buildx_support //enterprise/tools/build_images/lib:check_buildx_support

package(default_visibility = ["//enterprise:__subpackages__"])
