load("@io_bazel_rules_go//go:def.bzl", "go_test")

package(default_visibility = ["//cli:__subpackages__"])

exports_files(
    [
        "testdata/1.binpb.zst",
        "testdata/2.binpb.zst",
    ],
    visibility = ["//cli:__subpackages__"],
)
